// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtlPyM-ewdwmR__0yO2VIDMWr2VGdSWr0',
    appId: '1:624066079301:web:5ca8d7b1887c38a6e8512c',
    messagingSenderId: '624066079301',
    projectId: 'flutter-chat-app-cfa75',
    authDomain: 'flutter-chat-app-cfa75.firebaseapp.com',
    storageBucket: 'flutter-chat-app-cfa75.firebasestorage.app',
    measurementId: 'G-11VKE0F80B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0QhAD6BxYx3sWOtoVoIBshd2ttQNRYws',
    appId: '1:624066079301:android:4d6ae11df25416ffe8512c',
    messagingSenderId: '624066079301',
    projectId: 'flutter-chat-app-cfa75',
    storageBucket: 'flutter-chat-app-cfa75.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfrQ9vGHa5axbGJ1xWhOWDi4CbwbULBVg',
    appId: '1:624066079301:ios:720c24b6cada1555e8512c',
    messagingSenderId: '624066079301',
    projectId: 'flutter-chat-app-cfa75',
    storageBucket: 'flutter-chat-app-cfa75.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfrQ9vGHa5axbGJ1xWhOWDi4CbwbULBVg',
    appId: '1:624066079301:ios:720c24b6cada1555e8512c',
    messagingSenderId: '624066079301',
    projectId: 'flutter-chat-app-cfa75',
    storageBucket: 'flutter-chat-app-cfa75.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAtlPyM-ewdwmR__0yO2VIDMWr2VGdSWr0',
    appId: '1:624066079301:web:3249a9b119dc4d01e8512c',
    messagingSenderId: '624066079301',
    projectId: 'flutter-chat-app-cfa75',
    authDomain: 'flutter-chat-app-cfa75.firebaseapp.com',
    storageBucket: 'flutter-chat-app-cfa75.firebasestorage.app',
    measurementId: 'G-27N2ZGDVX1',
  );

}